### PR TITLE
Add an 'NTRBoot Quick Start Guide'

### PR DESCRIPTION
**Pull request by Deletecat**
Preview site: [https://wiki-testing.surge.sh](https://wiki-testing.surge.sh) - I put it on surge instead of cloudflare pages because it wasn't deploying properly, probably my fault though.

I've noticed that some people are confused about ntrboot carts. It's usually people getting the 'r4isdhc' carts mixed up; trying to use the ace3ds+ clones instead of the timebomb carts for ntrboot. Some people have also bought a DSTT to use with their 3DS. I made this page to show which carts are still being sold and which carts to avoid.

I think it might also be helpful for people who can't buy stuff from China - helps to determine which carts they should/shouldn't buy on their local markets.

I've also change the home page a wee bit, I've put the ntrboot quick start guide and the ysmenu compatibility list underneath the DS quick start guide,

What do you think?

### CODE REVIEW

**Comment by Sanrax** [comment]
Should the timebomb column still be kept? IMO it's irrelevant now, since YSMenu and the de-timebombed 1.85 kernel both don't have timebombs, which means those carts will work on any date.

**Comment by Sanrax** [comment]
Also, the YSMenu R4i-SDHC link in the table should be changed to this: https://wiki-testing.surge.sh/ysmenu-compat-ext#r4i-sdhc-ysmenu-folder

(In order to direct link to the relevant section of the page)

Would you be able to add that commit for me to your branch?

**Comment by Sanrax** [comment]
I also think that in the warning section, in things to look out for, the URL should be the number one thing to check, rather than number 3. It's the easiest way to tell an Ace3DS+ clone from an NTRBoot compatible demon cart.

Otherwise, I think this is ready to merge to main.

**Review by Sanrax — APPROVED** [review]

**Comment by Deletecat** [comment]
> Should the timebomb column still be kept?

To be honest, I'm somewhat mixed between keeping it or getting rid of it. I might add extra info in the notes column about it.

**Comment by Deletecat** [comment]
I removed it. I've also added a note about the timebomb for the carts which have them.

**Comment by lifehackerhansol** [comment]
> Should the timebomb column still be kept? IMO it's irrelevant now, since YSMenu and the de-timebombed 1.85 kernel both don't have timebombs, which means those carts will work on any date.

imo yes, until the official site gets their shit together and _actually_ remove the bomb + make it work.

But maybe it doesn't exactly belong in the ntrboot table.

**Comment by Sanrax** [comment]
> > Should the timebomb column still be kept? IMO it's irrelevant now, since YSMenu and the de-timebombed 1.85 kernel both don't have timebombs, which means those carts will work on any date.
> 
> imo yes, until the official site gets their shit together and _actually_ remove the bomb + make it work.
> 
> But maybe it doesn't exactly belong in the ntrboot table.

Fair enough. But when purchasing one for ntrboot reasons, the timebomb really doesn't matter at all. The user will be able to flash ntrboot at any time in the future without worrying about it.

**Comment by lifehackerhansol** [comment]
> Fair enough. But when purchasing one for ntrboot reasons, the timebomb really doesn't matter at all. The user will be able to flash ntrboot at any time in the future without worrying about it.

This only applies if the user has a second, hacked 3DS, which won't care about booting into the flashcart at all and do it right from the console. And at that point, maybe you should consider kartdlphax (whether they got mario kart 7 legally or not is not my concern)

But, if the user only has one, unhacked console, then they still need to boot to the kernel and launch ntrboot_flasher_nds from there, which means after 2024 they will still be screwed by the timebomb.

As I said, maybe it's not _too_ important for ntrboot. It's just my 2 cents.

**Comment by Sanrax** [comment]
> This only applies if the user has a second, hacked 3DS, which won't care about booting into the flashcart at all and do it right from the console. 

No, because there is now two kernels that can boot on those timebomb carts without any timebomb, meaning the ntrboot_flasher.nds will be able to be used no matter the date on the console. If they run into the timebomb, they'll most likely find YSMenu and will be able to use that to boot the flasher file.

**Comment by lifehackerhansol** [comment]
> No, because there is now two kernels that can boot on those timebomb carts without any timebomb, meaning the ntrboot_flasher.nds will be able to be used no matter the date on the console. If they run into the timebomb, they'll most likely find YSMenu and will be able to use that to boot the flasher file.

That was never my point.

My point is that until the actual, official site (being r4i-sdhc.com, r4isdhc.com and even sites that are now defunct) releases an actually functional kernel without a timebomb, it is timebombed as far as I'm concerned. It wasn't about whether you can make an alternative loader work or whether the timebomb in question was unofficially removed, it's about informing the user that if at some point after 2024 the manufacturer idiots still haven't got their stuff together, then the average user who are still using the stock kernel because they don't care while it works, never mind the fact we advertise YSMenu literally everywhere, will run into it.

It's definitely a valid question a user may ask. Yes, you can just slap another loader. Yes, it's really not that important. But what's the harm from adding a sub note? People are going to ask ***anyway***, what with so many stories about timebombs on the Internet, so can we not shut them up first?

**Comment by lifehackerhansol** [comment]
This wasn't really meant to become a long drawn discussion, I thought it was simply worth answering a question that constantly gets asked in r/flashcarts if for nothing else than to simply reduce the amount of people asking.

Ultimately, it doesn't matter whether it makes its way in or not given this is an ntrboot page and not a "is this cart bad to get" guide, but I really don't think it's that bad an idea. There's never any harm from more information; that's what this site is about, isn't it?

**Comment by Deletecat** [comment]
The timebomb is mentioned in the notes, I didn't remove it all together :p 
I think the timebomb should be mentioned on the page, but I don't really think it needs an entire column for it. Besides most people don't really know about the nop'd timebomb kernel. I've also added a note about the 4.1b kernel in the r4isdhc.com cart section because of it's broken rom loader.

**Comment by Deletecat** [comment]
if there's anything else to be added or changed, let me know :)
I've updated the preview at [https://wiki-testing.surge.sh/ntrboot-ds-carts](https://wiki-testing.surge.sh/ntrboot-ds-carts)

**Comment by Deletecat** [comment]
#7 - I think this would also be a good idea to implement for this page.

I've noticed on the preview site that the table just becomes a mess on mobile - one row takes up an entire page and the notes column becomes hard to read. 

It's late at night for me right now, though I could probably get round to adding it tomorrow!

**Comment by Sanrax** [comment]
I personally like the tables more, but yes, the tables do go off screen in mobile. I feel like the tabs UI for quick start guide looks less organized than tables though, so I'm a bit conflicted over which is the better option.

**Comment by Deletecat** [comment]
I'd probably take anything over this;
Screenshot_2023-08-13-09-09-07-47_3aea4af51f236e4932235fdada7d1643

**Comment by Deletecat** [comment]
I think it looks better with the tabs: <https://wiki-testing.surge.sh/ntrboot-ds-carts>

It also doesn't look horrendous on mobile either!

**Review by lifehackerhansol — APPROVED** [review]

**Pull request merged**
