### PR TITLE
Photo "fix"

### PR DESCRIPTION
**Pull request by Deletecat**
Adds an underline to the cart names, long enough to make the images the correct size. Janky but it works :p

### CODE REVIEW

**Comment by lifehackerhansol** [comment]
What happened to the entire file
did someone use CRLF

**Comment by Deletecat** [comment]
don't really know how that happened tbh
git usually changes the file but for some reason that didn't happen

**Comment by Deletecat** [comment]
thanks lol

**Comment by Deletecat** [comment]
ignore that, sorry, forgot to put the test stuff in a different branch

**Review by Sanrax — APPROVED** [review]
Looks good, I say we go ahead and merge to main.

**Comment by Sanrax** [comment]
Alright, I think it's now at the point that it's pretty useable. Great job, DeleteCat.

**Pull request merged**
