### PR TITLE
Rewrite DS Quick Start Guide to Table Format

### PR DESCRIPTION
**Pull request by Sanrax**
Rewriting DS Quick Start Guide page into a table format - added more images, fixed grammar and sentence structure, and added extra information.

### CODE REVIEW

**Review by Deletecat — APPROVED** [review]
I've had a quick look through and it looks good!

> Alternative Options and Flashcart Blacklists - DSi/3DS Users

I would probably change that to be 'Alternative Options for DSi/3DS Users', removing the mention of Flashcart Blocklists. I think that could be put in the Read Me section instead!

**Comment by Sanrax** [comment]
> I would probably change that to be 'Alternative Options for DSi/3DS Users', removing the mention of Flashcart Blocklists. I think that could be put in the Read Me section instead!

Sounds good, you can go ahead and make those changes for me if you'd like.

**Comment by lifehackerhansol** [comment]
The unordered lists don't seem to work in the tables.

**Comment by lifehackerhansol** [comment]
Worked around it; it can be cleaned up another day.

**Review by lifehackerhansol — APPROVED** [review]

**Comment by Sanrax** [comment]
> Worked around it; it can be cleaned up another day.

Awesome, great work. I couldn't find any other cleaner way to do unordered lists in markdown tables, so the `<ul><li>` is how I handled it. I don't exactly like the run on one-liners that the tables are, but that was the best I could find.

Regarding the relative links for images - I just didn't realize it's a problem. The .md page rel linked them when I cloned the repo, so I assumed that's how you wanted the images linked. The other markdown pages with images are likely also using rel-links, so we may want to fix that sometime.

**Comment by Deletecat** [comment]
> The .md page rel linked them when I cloned the repo

My fault, sorry :p 
It's mostly a habit from my other sites

**Comment by lifehackerhansol** [comment]
> Regarding the relative links for images - I just didn't realize it's a problem. The .md page rel linked them when I cloned the repo, so I assumed that's how you wanted the images linked. The other markdown pages with images are likely also using rel-links, so we may want to fix that sometime.

It's not a problem per se, and it totally works. It's just that it can potentially break if we ever move files around (i.e., if we for whatever reason add translations, and start having directories like `/fr_FR/ds-quick-start-guide.html`, then rel-links would break.) We know that we will only host images in one place, so there's no harm in doing a full link.

**Pull request merged**
